# Model arguments
model_name_or_path: lhkhiem28/zephyr-7b-sft-iter0
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixture:
  datasets:
    - id: lhkhiem28/ultrafeedback-sft-iter1
      config: default
      split: train_prefs
      columns:
        - chosen
      weight: 1.0
  seed: 0
max_seq_length: 2048
dataset_num_proc: 16

# SFT trainer config
seed: 42
bf16: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
gradient_accumulation_steps: 2
optim: adamw_torch
learning_rate: 2.0e-05
lr_scheduler_type: cosine
warmup_ratio: 0.1
per_device_train_batch_size: 16
num_train_epochs: 2
log_level: info
logging_strategy: steps
logging_steps: 5
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
output_dir: output/zephyr-7b-sft-iter1
overwrite_output_dir: true
push_to_hub: true
hub_model_id: zephyr-7b-sft-iter1
hub_strategy: every_save